# Generated by Django 5.2.4 on 2026-07-08 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouses.location'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_to', to='inventory.unit'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['warehouse', 'item'], name='balance_wh_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('item', 'warehouse', 'location'), name='uq_stock_balance_location'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'warehouse', 'created_at'], name='movement_item_wh_date_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name_ar', 'is_active'], name='item_name_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('item', 'from_unit', 'to_unit'), name='uq_item_unit_conversion'),
        ),
    ]
