# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconversion',
            name='factor',
            field=models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
